image: node:latest

npm:client:
    tags:
        - node
    stage: npm
    artifacts:
        paths:
            - client/node_modules/
        expire_in: 2 days
        when: always

    script:
        - cd client/
        - echo "Running npm ci ..."
        - npm ci
    only:
        changes:
            - client/**/*

lint:client:
    stage: lint
    tags:
        - node
    script:
        - cd client/
        - echo "Linting.."
        - npm run lint-fix
        - npm run tsc --silent
    except:
        - staging
    only:
        changes:
            - client/**/*

# --- Testing ---
.test_coverage_template: &test_coverage_report_configuration
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

test-unit:client:
    <<: *test_coverage_report_configuration
    stage: test-unit
    tags:
        - node
    script:
        - cd client/
        - echo "Testing.."
        - npm run test:unit
    except:
        - staging
    only:
        changes:
            - client/**/*

test-integration:client:
    <<: *test_coverage_report_configuration
    stage: test-integration
    tags:
        - node
    script:
        - cd client/
        - echo "Testing.."
        - npm run test:integration
    except:
        - staging
    only:
        changes:
            - client/**/*

test-e2e-staging:client:
    stage: test-e2e-staging
    image: mcr.microsoft.com/playwright:focal
    variables:
        REACT_APP_FRONTEND_URL: 'https://staging-monsters.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames-staging.herokuapp.com/'
    script:
        # - sleep 30
        - cd client/
        - npx playwright install --with-deps
        - echo "End to End testing.."
        - npm run test:e2e
    except:
            - staging
    only:
        # refs:
        #     - dev
        changes:
            - client/**/*

test-e2e-production:client:
    stage: test-e2e-production
    image: mcr.microsoft.com/playwright:focal
    variables:
        REACT_APP_FRONTEND_URL: 'https://monstrous-minigames.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames.herokuapp.com/'
    script:
        - sleep 30
        - cd client/
        - npx playwright install --with-deps
        - echo "End to End testing.."
        - npm run test:e2e
    only:
        refs:
            - dev
        changes:
            - client/**/*

#--- Deployment ---
.some-script: &deployment-script
    - cd client
    - CI=false npm run build
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN $DEPLOYMENT_DESTINATION
    - firebase deploy --only hosting -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

staging:client:
    stage: staging
    variables:
        REACT_APP_FRONTEND_URL: 'https://staging-monsters.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames-staging.herokuapp.com/'
        DEPLOYMENT_DESTINATION: staging
    environment:
        name: staging-client
        url: https://staging-monsters.web.app/
    script:
        - *deployment-script
    only:
        refs:
            - dev
            - staging
        changes:
            - client/**/*

production:client:
    stage: production
    variables:
        REACT_APP_FRONTEND_URL: 'https://monstrous-minigames.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames.herokuapp.com/'
        DEPLOYMENT_DESTINATION: production
    environment:
        name: production-client
        url: https://monstrous-minigames.web.app/
    script:
        - *deployment-script
    only:
        refs:
            - dev
            - master
        changes:
            - client/**/*
    when: manual
