image: node:latest

npm:client:
    tags:
        - node
    stage: npm
    artifacts:
        paths:
            - client/node_modules/
        expire_in: 2 days
        when: always

    script:
        - cd client/
        - echo "Running npm ci ..."
        - npm ci
    except:
        - /^backend-.*$/

lint:client:
    stage: lint
    tags:
        - node
    script:
        - cd client/
        - echo "Linting.."
        - npm run lint-fix
    except:
        - /^backend-.*$/

test:client:
    stage: test
    tags:
        - node
    script:
        - cd client/
        - echo "Testing.."
        - ./node_modules/.bin/jest ./
    except:
        - /^backend-.*$/

staging:client:
    stage: staging
    variables:
        REACT_APP_FRONTEND_URL: 'https://staging-monsters.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames-staging.herokuapp.com/'
    environment:
        name: staging-client
        url: https://staging-monsters.web.app/
    script:
        - cd client
        - CI=false npm run build
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_TOKEN staging
        - firebase deploy --only hosting -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

    only:
        - dev
    when: manual

production:client:
    stage: production
    variables:
        REACT_APP_FRONTEND_URL: 'https://monsters-6baec.web.app/'
        REACT_APP_BACKEND_URL: 'https://monstrous-minigames.herokuapp.com/'
    environment:
        name: production-client
        url: https://monsters-6baec.web.app/
    script:
        - cd client
        - CI=false npm run build
        - npm install -g firebase-tools
        - firebase use --token $FIREBASE_TOKEN production
        - firebase deploy --only hosting -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN

    only:
        - master
