image: node:15
stages:
  - npm
  - lint
  - test-unit
  - test-integration
  - test-component
  - staging
  - test-e2e
  - production

include:
  - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"
