image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - npm
  - lint
  - test
  - staging
  - production

# before_script:
#   - docker login -u natashatroth -p $DOCKER_TOKEN $CI_REGISTRY

# build:
#   stage: build
#   script:
#     - docker build --pull -t $CONTAINER_TEST_IMAGE .
#     - docker push $CONTAINER_TEST_IMAGE
# before_script:
#   # - docker login registry.example.com -u natashatroth -p $DOCKER_TOKEN
#   # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
#   - docker login -u natashatroth -p $DOCKER_TOKEN $CI_REGISTRY
include:
  # - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"
