image: node:15
stages:
  - npm
  - end-to-end
  - lint
  - test-unit
  - test-integration
  - test-other
  - staging
  - production

include:
  - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"
