image: node:15
stages:
  - npm
  - lint
  - test-unit
  - test-integration
  - staging-server
  - test-e2e
  - staging-client
  - production

include:
  - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"
