image: node:15
stages:
  - npm
  - lint
  - test-e2e-staging
  - test-unit
  - test-integration
  - staging
  - production
  - test-e2e-production

include:
  - local: "/server/.gitlab-ci.yml"
  - local: "/client/.gitlab-ci.yml"
