export enum CatchFoodMsgType {
    CREATE = 'game1/create',
    INITIAL_GAME_STATE_INFO = 'game1/initialGameState',
    START = 'game1/start',
    PHASER_GAME_LOADED = 'game1/phaserGameLoaded',
    PHASER_LOADING_TIMED_OUT = 'game1/phaserLoadingTimedOut',
    ALL_SCREENS_PHASER_GAME_LOADED = 'game1/allScreensPhaserGameLoaded',
    START_PHASER_GAME = 'game1/startPhaserGame',
    HAS_STARTED = 'game1/hasStarted',
    MOVE = 'game1/runForward',
    OBSTACLE = 'game1/obstacle',
    GAME_STATE = 'game1/gameState',
    OBSTACLE_SOLVED = 'game1/obstacleSolved',
    OBSTACLE_SKIPPED = 'game1/obstacleSkipped',
    PLAYER_FINISHED = 'game1/playerFinished',
    PLAYER_DIED = 'game1/playerDied',
    PLAYER_STUNNED = 'game1/playerStunned',
    PLAYER_UNSTUNNED = 'game1/playerUnstunned',
    STUN_PLAYER = 'game1/stunPlayer',
}
