image: node:latest

npm:server:
    tags:
        - node
    stage: npm
    artifacts:
        paths:
            - server/node_modules/
        expire_in: 2 days
        when: always

    script:
        - cd server/
        - echo "Running npm ci ..."
        - npm ci
    except:
        - /^frontend-.*$/

lint:server:
    stage: lint
    tags:
        - node
    script:
        - cd server/
        - echo "Linting.."
        - npm run lint
    except:
        - /^frontend-.*$/

test:server:
    stage: test
    tags:
        - node
    script:
        - cd server/
        - echo "Testing.."
        - ./node_modules/.bin/jest ./
    except:
        - /^frontend-.*$/

# --- Deployment ---
.job_template: &deployment_configuration
    tags:
        - node
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - cd server/
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip-cleanup

staging:server:
    <<: *deployment_configuration
    stage: staging
    # tags:
    #     - node
    environment:
        name: staging-server
        url: https://monstrous-minigames-staging.herokuapp.com/
    variables:
        HEROKU_APP: $HEROKU_APP_STAGING

    # script:
    #     - apt-get update -qy
    #     - apt-get install -y ruby-dev
    #     - gem install dpl
    #     - cd server/
    #     - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --skip-cleanup
    # only:
    #     - master

production:server:
    <<: *deployment_configuration

    stage: production
    # tags:
    #     - node
    # image: ruby:latest
    environment:
        name: production-server
        url: https://monstrous-minigames.herokuapp.com/
    variables:
        HEROKU_APP: $HEROKU_APP_PRODUCTION

    # script:
    #     - apt-get update -qy
    #     - apt-get install -y ruby-dev
    #     - gem install dpl
    #     - cd server/
    #     - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --skip-cleanup
    # only:
    #     - master
    when: manual
