image: node:latest

npm:server:
    tags:
        - node
    stage: npm
    artifacts:
        paths:
            - server/node_modules/
        expire_in: 2 days
        when: always

    script:
        - cd server/
        - echo "Running npm ci ..."
        - npm ci
    only:
        changes:
            - server/**/*

lint:server:
    stage: lint
    tags:
        - node
    script:
        - cd server/
        - echo "Linting.."
        - npm run lint
    except:
        - staging
    only:
        changes:
            - server/**/*

# --- Testing ---
.test_coverage_template: &test_coverage_report_configuration
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    # artifacts:
    #     when: always
    #     reports:
    #         junit:
    #             - junit.xml
    #         cobertura: coverage/cobertura-coverage.xml

test-unit:server:
    <<: *test_coverage_report_configuration
    stage: test-unit
    tags:
        - node
    script:
        - cd server/
        - echo "Testing.."
        - npm run test:unit
    except:
        - staging
    only:
        changes:
            - server/**/*

test-integration:server:
    <<: *test_coverage_report_configuration
    stage: test-integration
    tags:
        - node
    script:
        - cd server/
        - echo "Testing.."
        - npm run test:integration
    except:
        - staging
    only:
        changes:
            - server/**/*

# --- Deployment ---
.deployment_template: &deployment_configuration
    tags:
        - node
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - cd server/
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip-cleanup

staging:server:
    <<: *deployment_configuration
    stage: staging
    environment:
        name: staging-server
        url: https://monstrous-minigames-staging.herokuapp.com/
    variables:
        HEROKU_APP: $HEROKU_APP_STAGING
    only:
        refs:
            - dev
            - staging
        changes:
            - server/**/*

production:server:
    <<: *deployment_configuration
    stage: production
    environment:
        name: production-server
        url: https://monstrous-minigames.herokuapp.com/
    variables:
        HEROKU_APP: $HEROKU_APP_PRODUCTION
    only:
        refs:
            - dev
            - master
        changes:
            - server/**/*
    when: manual
