export const initialGameInput = {
    roomId: 'ZVSH',
    trackLength: 900,
    numberOfObstacles: 4,
    playersState: [
        // {
        //     id: '2r9HDAldY',
        //     name: 'test',
        //     positionX: 600,
        //     obstacles: [
        //         { id: 5, positionX: 293, type: 'TREE_STUMP', skippable: true },
        //         { id: 3, positionX: 410, type: 'TRASH', skippable: false },
        //         { id: 2, positionX: 660, type: 'STONE', skippable: false },
        //         { id: 1, positionX: 860, type: 'SPIDER', skippable: false },
        //     ],

        //     atObstacle: false,
        //     canSkipObstacle: false,
        //     finished: false,
        //     finishedTimeMs: 0,
        //     dead: false,
        //     rank: 0,
        //     isActive: true,
        //     stunned: false,
        //     characterNumber: 0,
        //     numberStonesThrown: 0,
        // },
        // {
        //     id: '2r9HDAldY',
        //     name: 'test',
        //     positionX: 600,
        //     obstacles: [
        //         { id: 5, positionX: 293, type: 'TREE_STUMP', skippable: true },
        //         { id: 3, positionX: 410, type: 'TRASH', skippable: false },
        //         { id: 2, positionX: 660, type: 'STONE', skippable: false },
        //         { id: 1, positionX: 860, type: 'SPIDER', skippable: false },
        //     ],

        //     atObstacle: false,
        //     canSkipObstacle: false,
        //     finished: false,
        //     finishedTimeMs: 0,
        //     dead: false,
        //     rank: 0,
        //     isActive: true,
        //     stunned: false,
        //     characterNumber: 0,
        //     numberStonesThrown: 0,
        // },
        // {
        //     id: '2r9HDAldY',
        //     name: 'test',
        //     positionX: 600,
        //     obstacles: [
        //         { id: 5, positionX: 293, type: 'TREE_STUMP', skippable: true },
        //         { id: 3, positionX: 410, type: 'TRASH', skippable: false },
        //         { id: 2, positionX: 660, type: 'STONE', skippable: false },
        //         { id: 1, positionX: 860, type: 'SPIDER', skippable: false },
        //     ],

        //     atObstacle: false,
        //     canSkipObstacle: false,
        //     finished: false,
        //     finishedTimeMs: 0,
        //     dead: false,
        //     rank: 0,
        //     isActive: true,
        //     stunned: false,
        //     characterNumber: 0,
        //     numberStonesThrown: 0,
        // },
        {
            id: '2r9HDAldY',
            name: 'test',
            positionX: 600,
            obstacles: [
                // { id: 2, positionX: 160, type: 'STONE', skippable: false },
                // { id: 2, positionX: 260, type: 'STONE', skippable: false },
                { id: 5, positionX: 293, type: 'TREE_STUMP', skippable: true },
                // { id: 2, positionX: 360, type: 'STONE', skippable: false },
                { id: 3, positionX: 410, type: 'TRASH', skippable: false },
                // { id: 2, positionX: 460, type: 'STONE', skippable: false },
                // { id: 2, positionX: 560, type: 'STONE', skippable: false },
                { id: 2, positionX: 660, type: 'STONE', skippable: false },
                { id: 1, positionX: 860, type: 'SPIDER', skippable: false },
            ],

            atObstacle: false,
            canSkipObstacle: false,
            finished: false,
            finishedTimeMs: 0,
            dead: false,
            rank: 0,
            isActive: true,
            stunned: false,
            characterNumber: 0,
            numberStonesThrown: 0,
        },
    ],
    gameState: 'CREATED',
    chasersPositionX: 100,
    cameraPositionX: 0,
};
