export enum Globals {
    MAX_PLAYER_NUMBER = 4,
    ROOM_TIME_OUT_HOURS = 5,
    ROOM_CLOSED_TIMEOUT_MIN = 5,
    GAME_STATE_UPDATE_MS = 33,
    CRON_JOB_CLEANUP = '*/10 * * * *',
    CHARACTER_COUNT = 4,
}
