const COUNTDOWN_TIME_GAME_START = 3000;
const NUMBER_PHOTO_TOPICS = 3;
const COUNTDOWN_TIME_TAKE_PHOTO = 6000;
const COUNTDOWN_TIME_VOTE = 6000;

export default {
    COUNTDOWN_TIME_GAME_START,
    NUMBER_PHOTO_TOPICS: NUMBER_PHOTO_TOPICS,
    COUNTDOWN_TIME_TAKE_PHOTO,
    COUNTDOWN_TIME_VOTE,
};
