const COUNTDOWN_TIME_GAME_START = 3000;
const NUMBER_ROUNDS = 4;
const COUNTDOWN_TIME_TAKE_PHOTO = 60000;
const COUNTDOWN_TIME_VOTE = 30000;
const COUNTDOWN_TIME_VIEW_RESULTS = 10000;
const COUNTDOWN_TIME_TAKE_FINAL_PHOTOS = 180000;

export default {
    COUNTDOWN_TIME_GAME_START,
    NUMBER_ROUNDS,
    COUNTDOWN_TIME_TAKE_PHOTO,
    COUNTDOWN_TIME_VOTE,
    COUNTDOWN_TIME_VIEW_RESULTS,
    COUNTDOWN_TIME_TAKE_FINAL_PHOTOS,
};
