export enum GameEventTypes {
    InitialGameStateInfoUpdate = 'INITIAL_GAME_STATE_INFO_UPDATE',
    ObstacleReached = 'OBSTACLE_REACHED',
    ApproachingSkippableObstacle = 'APPROACHING_SKIPPABLE_OBSTACLE',
    PlayerHasFinished = 'PLAYER_HAS_FINISHED',
    GameHasStarted = 'GAME_HAS_STARTED',
    GameHasPaused = 'GAME_HAS_PAUSED',
    GameHasResumed = 'GAME_HAS_RESUMED',
    GameHasStopped = 'GAME_HAS_STOPPED',
    GameHasFinished = 'GAME_HAS_FINISHED',
    PlayerHasDisconnected = 'PLAYER_HAS_DISCONNECTED',
    AllPlayersHaveDisconnected = 'ALL_PLAYERS_HAVE_DISCONNECTED',
    PlayerHasReconnected = 'PLAYER_HAS_RECONNECTED',
    PlayerIsDead = 'PLAYER_IS_DEAD',
    PlayerIsStunned = 'PLAYER_IS_STUNNED',
    ChasersWerePushed = 'CHASERS_WERE_PUSHED',
    PlayerHasPushedMaxNumberChasers = 'PLAYER_HAS_PUSHED_MAX_NUMBER_CHASERS',
    PlayerIsUnstunned = 'PLAYER_IS_UNSTUNNED',
}
